#------------------------------------------------------------
# Values for this website.
#------------------------------------------------------------

# Overall title for pages.
title: "Idaho COVID-19 Response Consortium"

#------------------------------------------------------------
# Generic settings (should not need to change).
#------------------------------------------------------------

# Magic to make URLs resolve both locally and on GitHub.
# See https://help.github.com/articles/repository-metadata-on-github-pages/.
# Please don't change it: <USERNAME>/<PROJECT> is correct.
repository: <USERNAME>/<PROJECT>

# Email address, no mailto:
#email: "ericjankowski@boisestate.edu"

# Set the default layout for things in the episodes collection.
defaults:
  - values:
      root: .
      layout: page

# Files and directories that are not to be copied.
exclude:

# Turn on built-in syntax highlighting.
highlighter: rouge
